<?php
declare(strict_types=1);

namespace AlbaStock\Services;

use mysqli;
use RuntimeException;

final class SalesService
{
    public function __construct(private readonly mysqli $db) {}

    public function create(array $actor, array $data): int
    {
        $enterprise=(int)$actor['entreprise_id']; $user=(int)$actor['id']; $branch=(int)($data['succursale_id']??$actor['succursale_id']??0);
        $clientId=isset($data['client_id'])&&$data['client_id']!==''?(int)$data['client_id']:null;
        $counterClientName=$clientId===null?trim((string)($data['client_comptoir_name']??'')):'';
        if($counterClientName!==''){$counterClientNameLength=preg_match_all('/./us',$counterClientName);if($counterClientNameLength===false||$counterClientNameLength>100)throw new RuntimeException('Le nom du client comptoir ne peut pas dépasser 100 caractères.');}
        if($counterClientName==='')$counterClientName=null;
        if($clientId===null&&$counterClientName===null)throw new RuntimeException('Le nom du client comptoir est obligatoire.');
        $lines=$data['items']??[]; $invoice=trim((string)($data['invoice_no']??''));
        if($branch<1||$invoice===''||!is_array($lines)||!count($lines)) throw new RuntimeException('Succursale, référence et au moins un produit sont requis.');
        $this->db->begin_transaction();
        try {
            $duplicate=$this->db->prepare('SELECT vente_id FROM ventes WHERE entreprise_id=? AND invoice_no=? LIMIT 1');$duplicate->bind_param('is',$enterprise,$invoice);$duplicate->execute();if($duplicate->get_result()->fetch_assoc())throw new RuntimeException('Cette référence de facture existe déjà.');
            if($clientId!==null){$client=$this->db->prepare('SELECT client_id FROM clients WHERE client_id=? AND entreprise_id=? LIMIT 1');$client->bind_param('ii',$clientId,$enterprise);$client->execute();if(!$client->get_result()->fetch_assoc())throw new RuntimeException('Client inconnu dans votre entreprise.');}
            $prepared=[];$currencyTotals=[];
            foreach($lines as $line){$productId=(int)($line['produit_id']??0);$quantity=(int)($line['quantity']??0);$discountEnabled=!empty($line['discount_enabled']);$discount=(float)($discountEnabled?($line['discount_amount']??0):0);
                if($productId<1||$quantity<1||!is_finite($discount)||$discount<0)throw new RuntimeException('Vérifiez les produits, quantités et réductions.');
                $product=$this->db->prepare('SELECT produit_id,name,sku,unit_price,monais,est_perisable FROM produits WHERE produit_id=? AND entreprise_id=? AND is_active=1 LIMIT 1');$product->bind_param('ii',$productId,$enterprise);$product->execute();$p=$product->get_result()->fetch_assoc();if(!$p)throw new RuntimeException('Un produit choisi est introuvable ou inactif.');
                $productCurrency=(string)$p['monais'];
                $isPerishable=(int)$p['est_perisable']===1;$stock=$this->db->prepare('SELECT quantity FROM stocks WHERE entreprise_id=? AND succursale_id=? AND produit_id=? FOR UPDATE');$stock->bind_param('iii',$enterprise,$branch,$productId);$stock->execute();$stockRow=$stock->get_result()->fetch_assoc();$before=(int)($stockRow['quantity']??0);
                if($isPerishable){$lotStock=$this->db->prepare("SELECT COALESCE(SUM(CASE WHEN d.date_expiration>=CURDATE() THEN d.quantity-d.quantity_out ELSE 0 END),0) AS available_quantity,COALESCE(SUM(d.quantity-d.quantity_out),0) AS on_hand_quantity FROM achat_details d JOIN achats a ON a.achat_id=d.achat_id AND a.entreprise_id=d.entreprise_id WHERE d.entreprise_id=? AND d.produit_id=? AND a.succursale_id=? AND a.movement_type='IN' AND a.status='RECEIVED'");$lotStock->bind_param('iii',$enterprise,$productId,$branch);$lotStock->execute();$lotStockRow=$lotStock->get_result()->fetch_assoc()?:[];if((int)($lotStockRow['available_quantity']??0)<$quantity)throw new RuntimeException('Stock insuffisant dans les lots non expirés de '.$p['name'].'.');$before=(int)($lotStockRow['on_hand_quantity']??0);}elseif($before<$quantity)throw new RuntimeException('Stock insuffisant pour '.$p['name'].'.');
                $unit=(float)$p['unit_price'];if($unit<=0){$manualUnitPrice=$line['unit_price']??null;if(!is_numeric($manualUnitPrice)||(float)$manualUnitPrice<=0)throw new RuntimeException('Saisissez un prix de vente positif pour '.$p['name'].'.');$unit=round((float)$manualUnitPrice,2);if($unit<=0)throw new RuntimeException('Le prix de vente doit être supérieur à zéro pour '.$p['name'].'.');}$gross=round($unit*$quantity,2);$discount=round($discount,2);if($discount>$gross)throw new RuntimeException('La réduction ne peut pas dépasser le total de '.$p['name'].'.');$discountPercent=$gross>0?round($discount*100/$gross,2):0.0;$subtotal=round($gross-$discount,2);$currencyTotals[$productCurrency]=round(($currencyTotals[$productCurrency]??0)+$subtotal,2);
                $prepared[]=['product'=>$p,'product_id'=>$productId,'quantity'=>$quantity,'before'=>$before,'unit_price'=>$unit,'discount_percent'=>$discountPercent,'discount_amount'=>$discount,'subtotal'=>$subtotal,'monais'=>$productCurrency];
            }
            $singleCurrency=count($currencyTotals)===1;$saleCurrency=$singleCurrency?(string)array_key_first($currencyTotals):null;$legacyTotal=$singleCurrency?(float)$currencyTotals[$saleCurrency]:0.0;$legacyPaid=0.0;
            $status='PENDING';
            $nullableCashId=null;$sale=$this->db->prepare('INSERT INTO ventes (entreprise_id,succursale_id,caisse_id,user_id,client_id,client_comptoir_name,invoice_no,total_amount,monais,amount_paid,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)');
            $sale->bind_param('iiiiissdsds',$enterprise,$branch,$nullableCashId,$user,$clientId,$counterClientName,$invoice,$legacyTotal,$saleCurrency,$legacyPaid,$status);$sale->execute();$saleId=(int)$this->db->insert_id;
            $currencyBalance=$this->db->prepare('INSERT INTO vente_totaux_monnaies (entreprise_id,vente_id,monais,total_amount,amount_paid) VALUES (?,?,?,?,0)');
            foreach($currencyTotals as $currency=>$currencyTotal){$currencyBalance->bind_param('iisd',$enterprise,$saleId,$currency,$currencyTotal);$currencyBalance->execute();}
            foreach($prepared as $item){$productId=$item['product_id'];$quantity=$item['quantity'];$unit=$item['unit_price'];$discountPercent=$item['discount_percent'];$discount=$item['discount_amount'];$subtotal=$item['subtotal'];
                $currency=$item['monais'];$detail=$this->db->prepare('INSERT INTO vente_details (entreprise_id,vente_id,produit_id,monais,quantity,unit_price,discount_percent,subtotal,discount_amount) VALUES (?,?,?,?,?,?,?,?,?)');$detail->bind_param('iiisidddd',$enterprise,$saleId,$productId,$currency,$quantity,$unit,$discountPercent,$subtotal,$discount);$detail->execute();$detailId=(int)$this->db->insert_id;
                if((int)$item['product']['est_perisable']===1){$lots=$this->db->prepare("SELECT d.achat_detail_id,d.quantity,d.quantity_out FROM achat_details d JOIN achats a ON a.achat_id=d.achat_id AND a.entreprise_id=d.entreprise_id WHERE d.entreprise_id=? AND d.produit_id=? AND a.succursale_id=? AND a.movement_type='IN' AND a.status='RECEIVED' AND d.date_expiration>=CURDATE() AND d.quantity>d.quantity_out ORDER BY d.date_expiration,d.achat_detail_id FOR UPDATE");$lots->bind_param('iii',$enterprise,$productId,$branch);$lots->execute();$remaining=$quantity;
                    foreach($lots->get_result()->fetch_all(MYSQLI_ASSOC) as $lot){$take=min($remaining,(int)$lot['quantity']-(int)$lot['quantity_out']);if($take<1)continue;$lotId=(int)$lot['achat_detail_id'];$update=$this->db->prepare('UPDATE achat_details SET quantity_out=quantity_out+? WHERE achat_detail_id=? AND entreprise_id=? AND quantity-quantity_out>=?');$update->bind_param('iiii',$take,$lotId,$enterprise,$take);$update->execute();if($update->affected_rows!==1)throw new RuntimeException('Un lot a changé pendant la vente. Recommencez.');$alloc=$this->db->prepare('INSERT INTO vente_detail_lots (entreprise_id,vente_detail_id,achat_detail_id,quantity) VALUES (?,?,?,?)');$alloc->bind_param('iiii',$enterprise,$detailId,$lotId,$take);$alloc->execute();$remaining-=$take;if($remaining===0)break;}
                    if($remaining>0)throw new RuntimeException('Lots non périmés insuffisants pour '.$item['product']['name'].'.');
                }
                $after=$item['before']-$quantity;
                if((int)$item['product']['est_perisable']===1){$stockUpdate=$this->db->prepare('INSERT INTO stocks (entreprise_id,succursale_id,produit_id,quantity) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity)');$stockUpdate->bind_param('iiii',$enterprise,$branch,$productId,$after);$stockUpdate->execute();}
                else{$stockUpdate=$this->db->prepare('UPDATE stocks SET quantity=quantity-? WHERE entreprise_id=? AND succursale_id=? AND produit_id=? AND quantity>=?');$stockUpdate->bind_param('iiiii',$quantity,$enterprise,$branch,$productId,$quantity);$stockUpdate->execute();if($stockUpdate->affected_rows!==1)throw new RuntimeException('Stock insuffisant pour '.$item['product']['name'].'.');}
                $type='SORTIE';$reference='VENTE';$note='Vente '.$invoice;$ledger=$this->db->prepare('INSERT INTO mouvements_stock (entreprise_id,succursale_id,produit_id,user_id,movement_type,quantity_before,quantity_moved,quantity_after,reference_type,reference_id,note) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$ledger->bind_param('iiiisiiisis',$enterprise,$branch,$productId,$user,$type,$item['before'],$quantity,$after,$reference,$saleId,$note);$ledger->execute();
            }
            $this->db->commit();return $saleId;
        }catch(\Throwable $e){$this->db->rollback();throw $e;}
    }

    public function collectPayment(array $actor, int $saleId, string $currency, float $amount, int $paymentModeId, ?int $cashId, string $reference = '', ?int $bankId = null): bool
    {
        $currency=trim($currency);
        if ($saleId < 1 || $currency === '' || $amount <= 0) throw new RuntimeException('Vente, monnaie et montant du paiement valides requis.');
        $enterprise=(int)$actor['entreprise_id'];$user=(int)$actor['id'];$this->db->begin_transaction();
        try {
            $q=$this->db->prepare('SELECT v.succursale_id,v.invoice_no,v.status FROM ventes v WHERE v.vente_id=? AND v.entreprise_id=? LIMIT 1 FOR UPDATE');
            $q->bind_param('ii',$saleId,$enterprise);$q->execute();$sale=$q->get_result()->fetch_assoc();
            if(!$sale)throw new RuntimeException('Vente introuvable.');
            if((int)($actor['succursale_id']??0)>0&&(int)$actor['succursale_id']!==(int)$sale['succursale_id'])throw new RuntimeException('Accès limité à une autre succursale.');
            if(!in_array($sale['status'],['PENDING','PARTIAL'],true))throw new RuntimeException('Cette vente n’est pas ouverte au paiement.');
            $currencyBalanceQuery=$this->db->prepare('SELECT total_amount,amount_paid FROM vente_totaux_monnaies WHERE entreprise_id=? AND vente_id=? AND monais=? LIMIT 1 FOR UPDATE');$currencyBalanceQuery->bind_param('iis',$enterprise,$saleId,$currency);$currencyBalanceQuery->execute();$currencyBalance=$currencyBalanceQuery->get_result()->fetch_assoc();if(!$currencyBalance)throw new RuntimeException('Cette facture ne contient aucun total dans la monnaie sélectionnée.');
            $modeQuery=$this->db->prepare("SELECT mode_paiement_id,code,requires_cash FROM modes_paiement WHERE mode_paiement_id=? AND is_active=1 AND code IN ('CASH','BANK','MOBILE_MONEY')");$modeQuery->bind_param('i',$paymentModeId);$modeQuery->execute();$mode=$modeQuery->get_result()->fetch_assoc();if(!$mode)throw new RuntimeException('Mode de paiement indisponible.');
            if(!$cashId||$cashId<1)throw new RuntimeException('Choisissez une caisse ouverte pour ce mode de paiement.');$cashQuery=$this->db->prepare("SELECT c.caisse_id,t.code,c.mode_paiement_id,c.banque_id FROM caisses c JOIN types_caisses t ON t.type_caisse_id=c.type_caisse_id AND t.entreprise_id=c.entreprise_id WHERE c.caisse_id=? AND c.entreprise_id=? AND c.succursale_id=? AND c.statut='OUVERTE' FOR UPDATE");$cashQuery->bind_param('iii',$cashId,$enterprise,$sale['succursale_id']);$cashQuery->execute();$cash=$cashQuery->get_result()->fetch_assoc();if(!$cash)throw new RuntimeException('La caisse choisie est fermée ou appartient à une autre succursale.');if((string)$cash['code']!==$currency)throw new RuntimeException('La monnaie de la caisse ne correspond pas à la monnaie du règlement.');if((int)$cash['mode_paiement_id']!==$paymentModeId)throw new RuntimeException('Le mode de paiement ne correspond pas à la caisse choisie.');if((int)$mode['requires_cash']!==1&&trim($reference)==='')throw new RuntimeException('La référence de paiement est obligatoire pour ce mode.');
            if((string)$mode['code']==='BANK'){if(!$bankId||$bankId<1)throw new RuntimeException('Choisissez la banque concernée par cette opération.');if($cash['banque_id']!==null&&(int)$cash['banque_id']!==$bankId)throw new RuntimeException('La banque choisie ne correspond pas à la banque associée à cette caisse.');$bank=$this->db->prepare('SELECT banque_id FROM banques WHERE banque_id=? AND entreprise_id=? AND is_active=1');$bank->bind_param('ii',$bankId,$enterprise);$bank->execute();if(!$bank->get_result()->fetch_assoc())throw new RuntimeException('La banque choisie est indisponible.');}elseif($bankId!==null&&$bankId>0)throw new RuntimeException('La banque ne peut être choisie que pour un paiement bancaire.');if((int)$mode['requires_cash']!==1&&trim($reference)==='')throw new RuntimeException('La référence de paiement est obligatoire pour ce mode.');
            $due=round((float)$currencyBalance['total_amount']-(float)$currencyBalance['amount_paid'],2);
            if($amount>$due+0.009)throw new RuntimeException('Le paiement dépasse le montant restant dû : '.$due.' '.$currency.'.');
            $newCurrencyPaid=round((float)$currencyBalance['amount_paid']+$amount,2);$updateCurrency=$this->db->prepare('UPDATE vente_totaux_monnaies SET amount_paid=? WHERE entreprise_id=? AND vente_id=? AND monais=?');$updateCurrency->bind_param('diis',$newCurrencyPaid,$enterprise,$saleId,$currency);$updateCurrency->execute();if($updateCurrency->affected_rows!==1)throw new RuntimeException('Le paiement de cette monnaie a déjà été enregistré.');
            $balances=$this->db->prepare('SELECT monais,total_amount,amount_paid FROM vente_totaux_monnaies WHERE entreprise_id=? AND vente_id=? FOR UPDATE');$balances->bind_param('ii',$enterprise,$saleId);$balances->execute();$balanceRows=$balances->get_result()->fetch_all(MYSQLI_ASSOC);$allPaid=true;$hasPaid=false;foreach($balanceRows as $balance){$balanceTotal=(float)$balance['total_amount'];$balancePaid=(float)$balance['amount_paid'];if($balancePaid>0)$hasPaid=true;if($balancePaid+0.009<$balanceTotal)$allPaid=false;}$newStatus=$allPaid?'PAID':($hasPaid?'PARTIAL':'PENDING');$legacyCurrency=count($balanceRows)===1?(string)$balanceRows[0]['monais']:null;$legacyTotal=count($balanceRows)===1?(float)$balanceRows[0]['total_amount']:0.0;$legacyPaid=count($balanceRows)===1?(float)$balanceRows[0]['amount_paid']:0.0;
            $updateSale=$this->db->prepare('UPDATE ventes SET total_amount=?,monais=?,amount_paid=?,status=? WHERE vente_id=? AND entreprise_id=? AND status IN (\'PENDING\',\'PARTIAL\')');$updateSale->bind_param('dsdsii',$legacyTotal,$legacyCurrency,$legacyPaid,$newStatus,$saleId,$enterprise);$updateSale->execute();
            $payment=$this->db->prepare('INSERT INTO paiements_ventes (entreprise_id,vente_id,mode_paiement_id,banque_id,caisse_id,user_id,amount,monais,reference) VALUES (?,?,?,?,?,?,?,?,?)');$paymentCashId=$cashId;$paymentBankId=$bankId;$payment->bind_param('iiiiiidss',$enterprise,$saleId,$paymentModeId,$paymentBankId,$paymentCashId,$user,$amount,$currency,$reference);$payment->execute();
            $type='ENTREE';$reason='Paiement vente '.$sale['invoice_no'];$bankReference=(string)$reference;$movement=$this->db->prepare('INSERT INTO mouvements_caisse (entreprise_id,caisse_id,user_id,mode_paiement_id,banque_id,bank_reference,type,amount,reason,reference_id) VALUES (?,?,?,?,?,?,?,?,?,?)');$movement->bind_param('iiiiissdsi',$enterprise,$cashId,$user,$paymentModeId,$paymentBankId,$bankReference,$type,$amount,$reason,$saleId);$movement->execute();$cashUpdate=$this->db->prepare('UPDATE caisses SET montant = montant + ? WHERE caisse_id=? AND entreprise_id=? AND statut="OUVERTE"');$cashDelta=(float)$amount;$cashUpdate->bind_param('dii',$cashDelta,$cashId,$enterprise);$cashUpdate->execute();if($cashUpdate->affected_rows!==1)throw new RuntimeException('Le solde de la caisse n’a pas pu être ajusté.');$this->db->commit();return $newStatus==='PAID';
        } catch(\Throwable $e) { $this->db->rollback(); throw $e; }
    }

    public function cancel(array $actor,int $saleId): void
    {
        $enterprise=(int)$actor['entreprise_id'];$user=(int)$actor['id'];$this->db->begin_transaction();
        try{$q=$this->db->prepare('SELECT succursale_id,caisse_id,invoice_no,amount_paid,sale_date,status FROM ventes WHERE vente_id=? AND entreprise_id=? LIMIT 1 FOR UPDATE');$q->bind_param('ii',$saleId,$enterprise);$q->execute();$sale=$q->get_result()->fetch_assoc();if(!$sale)throw new RuntimeException('Vente introuvable.');if((int)($actor['succursale_id']??0)>0&&(int)$actor['succursale_id']!==(int)$sale['succursale_id'])throw new RuntimeException('Accès limité à une autre succursale.');if($sale['status']==='CANCELLED')throw new RuntimeException('Cette vente est déjà annulée.');$unpaidPending=$sale['status']==='PENDING'&&(float)$sale['amount_paid']<=0;if(!$unpaidPending&&time()-strtotime((string)$sale['sale_date'])>=172800)throw new RuntimeException('Une vente déjà payée ne peut être annulée que pendant les 48 heures suivant sa création.');
            $details=$this->db->prepare('SELECT vente_detail_id,produit_id,quantity FROM vente_details WHERE entreprise_id=? AND vente_id=? FOR UPDATE');$details->bind_param('ii',$enterprise,$saleId);$details->execute();foreach($details->get_result()->fetch_all(MYSQLI_ASSOC) as $d){$product=(int)$d['produit_id'];$quantity=(int)$d['quantity'];$branch=(int)$sale['succursale_id'];$b=$this->db->prepare('SELECT quantity FROM stocks WHERE entreprise_id=? AND succursale_id=? AND produit_id=? FOR UPDATE');$b->bind_param('iii',$enterprise,$branch,$product);$b->execute();$before=(int)(($b->get_result()->fetch_assoc()['quantity']??0));$u=$this->db->prepare('UPDATE stocks SET quantity=quantity+? WHERE entreprise_id=? AND succursale_id=? AND produit_id=?');$u->bind_param('iiii',$quantity,$enterprise,$branch,$product);$u->execute();$lots=$this->db->prepare('SELECT achat_detail_id,quantity FROM vente_detail_lots WHERE entreprise_id=? AND vente_detail_id=? FOR UPDATE');$detailId=(int)$d['vente_detail_id'];$lots->bind_param('ii',$enterprise,$detailId);$lots->execute();foreach($lots->get_result()->fetch_all(MYSQLI_ASSOC) as $lot){$lotId=(int)$lot['achat_detail_id'];$lotQty=(int)$lot['quantity'];$restore=$this->db->prepare('UPDATE achat_details SET quantity_out=GREATEST(0,quantity_out-?) WHERE entreprise_id=? AND achat_detail_id=?');$restore->bind_param('iii',$lotQty,$enterprise,$lotId);$restore->execute();}$type='ENTREE';$reference='ANNULATION_VENTE';$note='Annulation vente '.$sale['invoice_no'];$ledger=$this->db->prepare('INSERT INTO mouvements_stock (entreprise_id,succursale_id,produit_id,user_id,movement_type,quantity_before,quantity_moved,quantity_after,reference_type,reference_id,note) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$after=$before+$quantity;$ledger->bind_param('iiiisiiisis',$enterprise,$branch,$product,$user,$type,$before,$quantity,$after,$reference,$saleId,$note);$ledger->execute();}
            $payments=$this->db->prepare('SELECT paiement_id,mode_paiement_id,banque_id,caisse_id,amount,reference FROM paiements_ventes WHERE entreprise_id=? AND vente_id=? AND payment_type=\'PAYMENT\' FOR UPDATE');$payments->bind_param('ii',$enterprise,$saleId);$payments->execute();$paymentRows=$payments->get_result()->fetch_all(MYSQLI_ASSOC);
            if($paymentRows){foreach($paymentRows as $paymentRow){$modeId=(int)$paymentRow['mode_paiement_id'];$paymentBankId=$paymentRow['banque_id']!==null?(int)$paymentRow['banque_id']:null;$paymentCashId=$paymentRow['caisse_id']!==null?(int)$paymentRow['caisse_id']:null;$amount=(float)$paymentRow['amount'];$refundReference='Remboursement annulation vente '.$sale['invoice_no'];$refund=$this->db->prepare("INSERT INTO paiements_ventes (entreprise_id,vente_id,mode_paiement_id,banque_id,caisse_id,user_id,amount,reference,payment_type) VALUES (?,?,?,?,?,?,?,?,'REFUND')");$refund->bind_param('iiiiiids',$enterprise,$saleId,$modeId,$paymentBankId,$paymentCashId,$user,$amount,$refundReference);$refund->execute();if($paymentCashId!==null){$type='SORTIE';$reason='Remboursement vente '.$sale['invoice_no'];$bankReference=(string)($paymentRow['reference']??'');$cash=$this->db->prepare('INSERT INTO mouvements_caisse (entreprise_id,caisse_id,user_id,mode_paiement_id,banque_id,bank_reference,type,amount,reason,reference_id) VALUES (?,?,?,?,?,?,?,?,?,?)');$cash->bind_param('iiiiissdsi',$enterprise,$paymentCashId,$user,$modeId,$paymentBankId,$bankReference,$type,$amount,$reason,$saleId);$cash->execute();$cashUpdate=$this->db->prepare('UPDATE caisses SET montant = montant - ? WHERE caisse_id=? AND entreprise_id=? AND statut="OUVERTE"');$cashDelta=(float)$amount;$cashUpdate->bind_param('dii',$cashDelta,$paymentCashId,$enterprise);$cashUpdate->execute();if($cashUpdate->affected_rows!==1)throw new RuntimeException('Le solde de la caisse n’a pas pu être ajusté au remboursement.');}}}
            elseif((float)$sale['amount_paid']>0&&(int)($sale['caisse_id']??0)>0){$type='SORTIE';$amount=(float)$sale['amount_paid'];$reason='Annulation vente '.$sale['invoice_no'];$cash=$this->db->prepare("INSERT INTO mouvements_caisse (entreprise_id,caisse_id,user_id,mode_paiement_id,type,amount,reason,reference_id) VALUES (?,?,?,(SELECT mode_paiement_id FROM modes_paiement WHERE code='CASH' LIMIT 1),?,?,?,?)");$cash->bind_param('iiisdsi',$enterprise,$sale['caisse_id'],$user,$type,$amount,$reason,$saleId);$cash->execute();$cashUpdate=$this->db->prepare('UPDATE caisses SET montant = montant - ? WHERE caisse_id=? AND entreprise_id=? AND statut="OUVERTE"');$cashDelta=(float)$amount;$cashUpdate->bind_param('dii',$cashDelta,(int)$sale['caisse_id'],$enterprise);$cashUpdate->execute();if($cashUpdate->affected_rows!==1)throw new RuntimeException('Le solde de la caisse n’a pas pu être ajusté à l’annulation.');}
            $update=$this->db->prepare("UPDATE ventes SET status='CANCELLED', cancellation_date=NOW() WHERE vente_id=? AND entreprise_id=? AND status<>'CANCELLED'");$update->bind_param('ii',$saleId,$enterprise);$update->execute();if($update->affected_rows!==1)throw new RuntimeException('La vente a déjà été modifiée.');$this->db->commit();
        }catch(\Throwable $e){$this->db->rollback();throw $e;}
    }
}
